name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build 'common'
        working-directory: ./common
        run: |
          npm install
          npm run build
          npm run generate
      # - name: Testing 'common'
      #   working-directory: ./common
      #   run: |
      #     npm run test
      - name: Build 'components'
        working-directory: ./components
        run: |
          npm install
          npm run build
      - name: Build 'geolocationapi'
        working-directory: ./geolocationapi
        run: |
          npm install
          npm run build
      - name: Build 'qrscanner'
        working-directory: ./qrscanner
        run: |
          npm install
          npm run build
          npm run generate
      - name: Build 'consumer'
        working-directory: ./consumer
        run: |
          npm install
          npm run build
      - name: Prepare deployment
        run: |
          mkdir ./_site
          mkdir ./_site/qrscanner
          mkdir ./_site/qrscanner/pages
          mkdir ./_site/geolocationapi
          mkdir ./_site/consumer
          
          cp -r ./qrscanner/dist/. ./_site/qrscanner/
          cp -r ./qrscanner/pages/. ./_site/qrscanner/pages/
          cp -r ./geolocationapi/dist/. ./_site/geolocationapi/
          cp -r ./consumer/dist/. ./_site/consumer/
          cp ./common/dist/tracking.ttl ./_site/tracking.ttl
          touch ./_site/index.html
      - name: Deploy site to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site